[package]
name = "pixel_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
simple_logger = "2.1.0"
log = "0.4.17"
pixels = "0.9.0"
fontdue = "0.7.2"
